### ISSUE TITLE
Navigation Link not proper

### ISSUE THREAD

**Issue by kuntal-b** [Microsoft/PowerBI-Angular#1]
A link for **PowerBI-Angular2** mentioned in document is incorrect . this [page](https://github.com/Microsoft/PowerBI-Angular2) in not found .

**Comment by mattmazzola** [comment]
The link is correct but the repository it links to is currently private which is likely why you're seeing page not found. We have not completed the Angular 2 library yet, but when it's finished we will make it public. The readme does say we 'will' have the library which I intended to mean coming in the future, but I can see how it's misleading if there is a link there. I'll remove the link and update the readme to be more clear.

**Comment by kuntal-b** [comment]
Thankx for clarification .
