### ISSUE TITLE
this.powerBiCoreService is undefined

### ISSUE THREAD

**Issue by whozDougie** [Microsoft/PowerBI-Angular#10]
Hi All,

Is there a specific way I have to add the directive? Or is there something I am doing wrong?

I've written a custom controller that obtains an embedUrl and accessToken and saves it to relevant variables which are then consumed by the template:

<powerbi-report embed-url="vm.report.embedUrl" access-token="vm.report.accessToken" options="vm.reportOptions"></powerbi-report>

My controller is able to get those values, but fails to render the directive. 

**The error I get is:**
this.powerBiCoreService is undefined
PowerBiService</PowerBiService.prototype.embed@https://localhost:44300/App/scripts/plugins/angular-powerbi.js:338:10
Controller</Controller.prototype.embed@https://localhost:44300/App/scripts/plugins/angular-powerbi.js:159:27
Controller</Controller.prototype.init/debouncedEmbed<@https://localhost:44300/App/scripts/plugins/angular-powerbi.js:119:18
Controller</Controller.prototype.debounce/</previousTimeoutPromise<@https://localhost:44300/App/scripts/plugins/angular-powerbi.js:173:75
f/r<@https://localhost:44300/Scripts/angular.min.js:158:244
e@https://localhost:44300/Scripts/angular.min.js:45:348
$f/k.defer/c<@https://localhost:44300/Scripts/angular.min.js:48:275

I traced the error back to angular-powerbi.js (328-359):

/* 3 */
/***/ function(module, exports) {

	"use strict";
	var PowerBiService = (function () {
	    /* tslint:enable:member-ordering */
	    function PowerBiService(powerbi) {
	        this.powerBiCoreService = powerbi;
	    }
	    PowerBiService.prototype.embed = function (element, config) {
	        return this.powerBiCoreService.embed(element, config);
	    };
	    PowerBiService.prototype.get = function (element) {
	        return this.powerBiCoreService.get(element);
	    };
	    PowerBiService.prototype.find = function (uniqueId) {
	        return this.powerBiCoreService.find(uniqueId);
	    };
	    PowerBiService.prototype.reset = function (element) {
	        this.powerBiCoreService.reset(element);
	    };
	    /* tslint:disable:member-ordering */
	    PowerBiService.$inject = [
	        'PowerBiGlobal'
	    ];
	    return PowerBiService;
	}());
	Object.defineProperty(exports, "__esModule", { value: true });
	exports.default = PowerBiService;

/***/ },

EDIT:
I added a reference to: 
<script src="powerbi.js"></script> (PowerBI-Client v2.0)
and it seemed to load reports.

If this is indeed a requirement, can you please update the official document on the wiki of this project please? Seems to be missing. Obviously, I didn't do a manual install as opposed to an npm install!

Thanks!

**Comment by mattmazzola** [comment]
You are correct. Both the scripts are required.  Since `powerbi.js` can be used as standalone solution it is not bundled with the angular-powerbi.js script and the angular-powerbi.js depends on the `powerbi` global to be defined. 

Ideally this would all use ES6 modules but this solution seemed less confusing.

You can see the `index.html` of our demo application uses both scripts:
https://github.com/Azure-Samples/powerbi-angular-client/blob/master/app/index.html#L19
