### ISSUE TITLE
Date filter

### ISSUE THREAD

**Issue by sheldonyss** [Microsoft/PowerBI-Angular#9]
I tried to filter my report by creating a Date filter but Power BI service always return this error: 
_undefined:1 Uncaught (in promise) Object {message: "Invalid filter definition"}_

Below is the TypeScript code of filter.
`    static predefinedFilter2 = new pbi.models.AdvancedFilter({
        table: "f_msANA_byRelease_transformed",
        column: "aaValuePeriodStartTime"
    }, "And",
        {
            operator: "GreaterThan",
            value: "1 June 2016"
        }
        // ,
        // {
        //     operator: "None",
        //     value: "2016-06-05 23:59:59"
        // }
    );`

Can anyone provide an example of filter report by date?

**Comment by mattmazzola** [comment]
I believe dates should be in the [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format.

In your case I think this would probably be: "2016-06-05T23:59:59Z".  The `Z` implies UTC time zone though, so you might need to use offsets or compute the value and using a library such as `moment` to make it easier.

Also, the construction of filter objects is not related to the angular code so I will close this issue. The angular components just pass the data through.  Try out the ISO 8601 format and if it still doesn't work re-open on the https://github.com/Microsoft/powerbi-models/issues/new repo
